# docker-compose.yml
services:
  api:
    build: ./api
    command: python /api/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/api
    ports:
      - 8000:8000
    depends_on:
      - db
  web:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: